vim.opt.number = true
vim.opt.relativenumber = false
vim.opt.cursorline = false
vim.opt.wrap = true
vim.opt.expandtab = false
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.clipboard = "unnamedplus"
vim.opt.swapfile = false
-- vim.opt.termguicolors = true
